### ISSUE TITLE
请问您可以提供将数据集生成六个相应文件的相应代码吗？

### ISSUE THREAD

**Issue by MooreAndMoore** [WHUIR/CARL#2]
如标题所示，我们想参考学习您的论文，想复现一次您的模型。感谢！

**Comment by angle233** [comment]
你可以在https://github.com/WHUIR/CARP/tree/master/dataPreprocessing下载预处理文件，可以输入Amazon-5core的原始文件得到相应的输出。

**Comment by lichenliang-whu** [comment]
你可以在 https://github.com/WHUIR/CARP/tree/master/dataPreprocessing 下载预处理文件，可以输入Amazon-5core的原始文件得到相应的输出。
